= Apex

Apex is a compendium of libraries for implementing web backends in
Clojure.

== Status

PRE-ALPHA:

Apex consists of a set of Ring-compatible middleware, configured with
OpenAPI. Some of this middleware will be marked as ready for use prior
to others. For now, this project is being developed in the open for
the purposes of soliticing feedback from the community and not
recommended for actual use in systems.

== Getting started

Start with the petstore example in `examples/petstore`. See
link:examples/petstore/README.adoc[].

Individual modules are:

params:: An implementation of OpenAPI parameter parsing.

oauth2:: An implementation of OpenID Connect upon OAuth2 driven by OpenID Connect Discovery configuration.


== Objective

Apex will be considered a success if it meets the following acceptance
criteria:

* Developers with limited experience of Clojure can create web APIs
  without too much difficulty, including security.

* Web APIs created with Apex are broadly conformant to HTTP standards
  and performance is acceptable for the vast majority of use-cases.

This requires the following:

* Error handling is informative and leads developers quickly to the
  actual cause of the error.

== Rationale

https://github.com/juxt/yada[yada], the web library we wrote to
replace Liberator, is beginning to show its age. When we started yada,
the web looked a little different than today:

* There was no async option in Ring, and we wanted to avoid the
  thread-per-request model for some of the high-traffic websites we
  were producing in our consulting projects.

* Prismatic Schema was firmly established as the way to specify
  constraints on data.

In the years since yada was conceived, designed and developed, there
have been a number of external developments:

* Ring now has a
  https://github.com/ring-clojure/ring/blob/master/SPEC[well thought
  out approach to async], supporting modern asynchronous web servers
  without sacrificing the composeability of middleware.

* https://www.openapis.org/[OpenAPI] (formerly Swagger) continues to
  attact users, adopted by large organisations, and has now matured
  and is now governed by The Linux Foundation.

* https://json-schema.org/[JSON Schema] continues to mature. (We like
  it so much we've even written our own Clojure library,
  https://github.com/juxt/jinx[jinx])

* Metosin has developed a very nice content negotiation and coercion
  library called https://github.com/metosin/muuntaja[Muuntaja]

=== OpenAPI: the missing piece of the web jigsaw

One of the key insights behind yada was web resources should be
modelled with data. OpenAPI is now firmly established as both the
_de-facto_ and the _de-jure_ data model of web APIs.

=== From Prismatic Schema to JSON Schema

The future of Prismatic Schema has been in doubt since Cognitect
announced clojure.spec. While we value clojure.spec in our internal
data structures, we feel that the web API community is going to move
inexorably towards adoption of JSON Schema. We believe the Clojure
community should welcome this trend towards a more data-oriented
approach to building application systems.

=== Standards conformance

Standards facilitate the rich interoperable ecosystem we enjoy as both
users and developers of the web. Too often conformance with
established standards is the exception rather than the rule. This is a
shame, as it degrades the web for everyone. Web libraries like Apex
should encourage compliance due to the multiplier effect of multiple
applications built on them.

== References

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests
* https://apisyouwonthate.com/blog/
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation
* http://httpd.apache.org/docs/current/en/content-negotiation.html#algorithm
* https://tools.ietf.org/html/rfc4918
* https://tools.ietf.org/html/rfc7230
* https://tools.ietf.org/html/rfc7231
* https://tools.ietf.org/html/rfc7232
* https://tools.ietf.org/html/rfc7233
* https://tools.ietf.org/html/rfc7234
* https://tools.ietf.org/html/rfc7235
* https://tools.ietf.org/html/rfc7237
* https://tools.ietf.org/html/rfc7617
* https://tools.ietf.org/html/rfc7616


== License

The MIT License (MIT)

Copyright © 2020 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
